name: Base image build
on:
  push:
    tags-ignore:
    branches:
      - main
      - mc970

  pull_request:

env:
  TAG: ${{ github.event_name == 'push' && github.ref_name || github.head_ref }}
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: lnls-debian-11-epics-7

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: cd base && JOBS=$(nproc) docker compose build
      - name: Log in to registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push tagged image
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: docker push $REGISTRY/$IMAGE_NAME:$TAG
      - name: Push latest image
        if: github.event_name == 'push' && github.ref_type == 'branch'
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:$TAG $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest
